[build]
  command = "pnpm run build"
  publish = "dist"

[dev]
  command = "pnpm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Handle OAuth redirects properly
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200